apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
bases:
- ../../base

commonLabels:
  env: prod

resources:
- namespace.yaml

patchesStrategicMerge:
- replicas-patch.yaml
