apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- network-policy.yaml

commonLabels:
  app.kubernetes.io/name: hello-world
  app.kubernetes.io/instance: prod
  app.kubernetes.io/part-of: devops-project

images:
- name: ${ACR_NAME}.azurecr.io/hello-world
  newName: ${ACR_NAME}.azurecr.io/hello-world
  newTag: latest  # This will be updated by CI pipeline
