name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build and Test
      run: |
        go test ./... || exit 1
        go build -v ./... || exit 1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and Push Docker image with SHA tag
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-world:${{ github.sha }} . || exit 1
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-world:${{ github.sha }} || exit 1

    - name: Update Kustomization
      run: |
        cd k8s/base || exit 1
        if ! sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" kustomization.yaml; then
          echo "Failed to update kustomization.yaml"
          exit 1
        fi
        
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add k8s/base/kustomization.yaml
        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push || exit 1